name: GKE DevOps Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-bc7a0df3-c037-4d41-86a
  GAR_LOCATION: asia-south1
  REPOSITORY: devops-repo
  IMAGE: gke-devops-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Authenticate Docker to Artifact Registry
      run: |
        echo "${{ secrets.GCP_ACCESS_TOKEN }}" | docker login -u oauth2accesstoken --password-stdin https://asia-south1-docker.pkg.dev

    - name: Build Docker Image
      run: |
        docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} ./app

    - name: Push Docker Image
      run: |
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}
