name: GKE DevOps Pipeline

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-bc7a0df3-c037-4d41-86a
  GAR_LOCATION: asia-south1
  REPOSITORY: devops-repo
  IMAGE: gke-devops-app
  GKE_CLUSTER: devops-gke-cluster
  GKE_ZONE: asia-south1-a

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_ACCESS_TOKEN }}" > token.txt

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

    - name: Build Docker Image
      run: |
        docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }} ./app

    - name: Push Docker Image
      run: |
        docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Update Kubernetes Deployment
      run: |
        kubectl set image deployment/devops-app-deployment \
        devops-app=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:${{ github.sha }}
